apiVersion: v1
kind: Service
metadata:
  name: api-service-tc
spec:
  #  ClusterIP torna o serviço acessível apenas DENTRO do cluster.
  type: ClusterIP
  selector:
    app: api-tc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
