apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations: 
    # Health probe na raiz 
    appgw.ingress.kubernetes.io/health-probe-path: "/"
spec:
  ingressClassName: azure-application-gateway 
  rules:
  - host: api.internal.techchallenge
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-service-tc
            port:
              number: 80